endpoints:
  - name: "todos-get"
    path: "/todos"
    method: "GET"
    destination:
      url: "https://jsonplaceholder.typicode.com/todos"
      headers:
        - key: "Content-Type"
          value: "application/json"
        - key: "Authorization"
          value: "Bearer ${AUTH_TOKEN}"
  - name: "todos-post"
    path: "/todos"
    method: "POST"
    destination:
      url: "https://jsonplaceholder.typicode.com/todos"
      headers:
        - key: "Content-Type"
          value: "application/json"
        - key: "Authorization"
          value: "Bearer ${AUTH_TOKEN}"
  - name: "posts"
    path: "/posts"
    method: "GET"
    destination:
      url: "https://jsonplaceholder.typicode.com/posts"
