name: Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
